name = "gpt-x"
main = "./src/server.js"
compatibility_date="2022-02-26"

account_id = "58e37118af2317e6056e1aa5d526780f"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
